Repository threeback/kicketing-front, pull requests merged in 2024-05, with the labels that each got.

#11 refact : 회원가입 api 경로 리펙토링
  src/routes/signup/+page.svelte
Labels: ♻️ refactor

#13 fix : 일반 로그인 기능 안되는 문제 수정
  src/routes/signin/+page.svelte
  src/routes/signup/+page.svelte
Labels: 🐛 bug

#17 Feat/#15 로그인페이지
  src/routes/signin/+page.svelte
Labels: 💫 feat

#20 Feature/#14 마이페이지
  .env
  .svelte-kit/ambient.d.ts
  .svelte-kit/generated/server/internal.js
  package-lock.json
  package.json
  src/lib/api.js
  src/lib/images/main/changmo_poster.jpeg
  src/lib/images/main/iu_poster.jpg
  src/lib/images/main/left.png
  src/lib/images/main/right.png
  src/lib/images/main/search.png
  src/lib/stores/auth.js
  src/routes/+layout.svelte
  src/routes/+page.svelte
  src/routes/UserState.svelte
  src/routes/about/+page.js
  src/routes/about/+page.svelte
  src/routes/callback/+page.svelte
  src/routes/mypage/+page.svelte
  src/routes/mypage/changeName/+page.svelte
  src/routes/mypage/tabs/address_tab.svelte
  src/routes/mypage/tabs/booking_tab.svelte
  src/routes/mypage/tabs/cancel_tab.svelte
  src/routes/mypage/tabs/privacy_tab.svelte
  src/routes/mypage/tabs/tabs.svelte
  src/routes/mypage/verify/+page.svelte
  src/routes/signin/+page.svelte
  src/routes/signin/google/callback/+page.svelte
  src/routes/signin/kakao/callback/+page.svelte
  src/routes/signin/naver/callback/+page.svelte
  static/style/button.css
  static/style/changeName.css
  static/style/container.css
  static/style/event.css
  static/style/privacy_tab.css
  vite.config.js
Labels: 💫 feat

#21 Feature/#14 마이페이지
  src/routes/mypage/tabs/booking_tab.svelte
  src/routes/mypage/tabs/cancel_tab.svelte
  src/routes/mypage/tabs/privacy_tab.svelte
  src/routes/mypage/tabs/tabs.svelte
  src/routes/signin/+page.svelte
Labels: 💫 feat

#23 Feature/#19 공연상세페이지
  .env
  src/routes/+page.svelte
  src/routes/UserState.svelte
  src/routes/goods/+page.svelte
  src/routes/mypage/+page.svelte
  src/routes/mypage/changeName/+page.svelte
  src/routes/mypage/tabs/booking_tab.svelte
  src/routes/mypage/tabs/cancel_tab.svelte
  src/routes/mypage/tabs/privacy_tab.svelte
  src/routes/styles.css
  static/style/button.css
  static/style/changeName.css
  static/style/container.css
  static/style/event.css
Labels: 💫 feat
