Repository threeback/kicketing-front, pull requests merged in 2024-06, with the labels that each got.

#25 feat : 공연 상세페이지 기능 API
  package-lock.json
  package.json
  src/lib/api.js
  src/routes/+page.svelte
  src/routes/goods/+page.svelte
Labels: 💫 feat

#27 Feature/#24 예매페이지
  src/lib/api.js
  src/lib/stores/auth.js
  src/routes/UserState.svelte
  src/routes/booking/+page.svelte
  src/routes/signin/+page.svelte
  src/routes/signin/google/callback/+page.svelte
  src/routes/signin/kakao/callback/+page.svelte
  src/routes/signin/naver/callback/+page.svelte
  static/style/privacy_tab.css
Labels: 💫 feat

#28 refact : 검색창을 사용하는 곳에서만 사용하게 수정
  src/routes/+page.svelte
  src/routes/Header.svelte
  src/routes/goods/+page.svelte
  src/routes/search/+page.svelte
Labels: 💫 feat

#29 fix : api 경로 버그
  src/lib/api.js
Labels: 🐛 bug

#32 refact : getBookableDates 다음 달 까지 가져오게 리팩토링
  src/routes/goods/+page.svelte
Labels: ♻️ refactor

#33 style : 좌석 줄바꿈 및 footer
  src/routes/+layout.svelte
  src/routes/goods/+page.svelte
Labels: ♻️ refactor

#36 feat : 이벤트 페이지 구현
  src/routes/additional_box.svelte
  src/routes/promotion/+page.svelte
  src/routes/ranking/+page.svelte
Labels: 💫 feat

#38 Feature/#37 공지사항페이지
  src/routes/+page.svelte
  src/routes/additional_box.svelte
  src/routes/notice/+page.svelte
  src/routes/promotion/+page.svelte
  src/routes/ranking/+page.svelte
Labels: 💫 feat

#40 feat : 고객센터 페이지 구현
  src/routes/additional_box.svelte
  src/routes/promotion/+page.svelte
  src/routes/service/+page.svelte
  static/FAQ.png
  static/QnA.png
  static/chatbotAI.png
  static/consultation.png
Labels: 💫 feat
